# Generated by Django 3.1.7 on 2021-03-16 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название картинки')),
                ('image', models.ImageField(upload_to='images/')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageMetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('high', models.CharField(max_length=10, verbose_name='Высота')),
                ('width', models.CharField(max_length=10, verbose_name='Ширина')),
                ('average_color', models.CharField(max_length=255, verbose_name='Средний цвет картинки')),
                ('average_color_image', models.ImageField(upload_to='medians/')),
                ('number_of_coins', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Количество монет')),
                ('sum_of_coins', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Сумма монет')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meta_picture.image', verbose_name='Картинка')),
            ],
        ),
    ]
